---
  - name: Copy mail aliases
    template: src=aliases.j2 dest=/etc/aliases owner=root group=root mode=0644

  - name: Copy mailname
    template: src=mailname.j2 dest=/etc/mailname owner=root group=root mode=0644

  - name: Set exim4 log to syslog.
    lineinline:
      path: /etc/exim4/conf.d/main/02_exim4-config_options
      state: present
      line: "log_file_path = syslog"
    when: exim4_log_to_syslog == true
